Repository gdsc-nits-org/veritas, pull requests merged in 2022-10, with the labels that each got.

#15 UPD: Permission update & Event get all
  src/controllers/event/get.ts
  src/routes/member.ts
Labels: hacktoberfest-accepted

#16 ADD: Technology Id, PATCH: technology Routes
  prisma/migrations/20221028111325_/migration.sql
  prisma/schema.prisma
  src/controllers/person/register.ts
  src/controllers/project/add.ts
  src/controllers/project/get.ts
  src/controllers/technology/delete.ts
  src/controllers/technology/get.ts
  src/controllers/technology/index.ts
  src/controllers/technology/update.ts
  src/global/errors/technology.ts
  src/routes/technology.ts
Labels: enhancement, hacktoberfest-accepted

#17 Project
  src/controllers/project/add.ts
  src/controllers/project/get.ts
  src/controllers/project/update.ts
  src/global/errors/domain.ts
  src/global/errors/index.ts
  src/utils/domain.ts
  src/utils/index.ts
  src/utils/project.ts
Labels: hacktoberfest-accepted

#19 FIX: technology schema, UPDATE: docs
  docs/swagger.yaml
  prisma/migrations/20221030063404_/migration.sql
  prisma/schema.prisma
Labels: documentation, hacktoberfest-accepted
